  controller_list:
    - name: explorer_arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - arm1_bearing_joint
        - arm2_arm1_joint
        - arm3_arm2_joint
        - pt1_arm_joint
        - pt2_pt1_joint
        - rotate_joint
    - name: explorer_gripper_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - finger1_finger2_joint
        - finger2_finger3_joint
        - finger3_joint
